### ISSUE TITLE
Deprecated

### ISSUE THREAD

**Issue by PEMapModder** [zzm317/AnimalWorld#2]
Don't use CallbackTask; it has already been deprecated.

And what about separating your code into different classes? Currently it looks a bit messy.

If you do these, the chance of hour plugin being approved is much higher.

**Comment by zzm317** [comment]
...This plugin ....I have already rewrite one...And it was cut into different files.

**Comment by zzm317** [comment]
But when i want to use a task...I just copy from old plugins...
so it was still CallBackTask...

**Comment by PocketKiller** [comment]
@zzm317 while you were selecting all issues (the spam ones) you closed this.
